version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: login
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"