spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: login
    password: pass
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

    hibernate:
      ddl-auto: create
    show-sql: true

calculate:
  advance-payment-percentage: 25
  income-per-shift: 1800
  advance-payment: 5000
  percentage-payment-enabled: true


